### ISSUE TITLE
Create S3 Bucket using Terraform

### ISSUE THREAD

**Issue by VishwaS-22** [VishwaS-22/AWS-CloudBoost#4]
Create a folder named aws-s3 under project Iac/Terraform then add your state files in that. ThankYou!

**Comment by ChisomJude** [comment]
assign this to me

**Comment by VishwaS-22** [comment]
Hey @ChisomJude! Assigned successfully, Make a PR with your Solution. Happy Contributions!

**Comment by ChisomJude** [comment]
done

**Comment by VishwaS-22** [comment]
Hey @ChisomJude! Thanks for Contributing to the Issue. Happy Contributions!
